steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/kibana-deployer:$_TAG", "."]
#    volumes:
#      - name: 'ssh'
#        path: /root/.ssh

images: ["gcr.io/$PROJECT_ID/kibana-deployer:$_TAG"]
