steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mythical-hyperion-kibana:$_TAG",
           "--build-arg", "env=$_ENV", "--build-arg", "port=$_PORT", "."]
#    volumes:
#      - name: 'ssh'
#        path: /root/.ssh

images: ["gcr.io/$PROJECT_ID/mythical-hyperion-kibana:$_TAG"]
